version: "3.7"

services:
  frontend:
    build:
      context: ./app_frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  backend:
    container_name: backend
    working_dir: /usr/share/nginx
    build:
      context: ./app_backend
      dockerfile: Dockerfile
    volumes:
      - ./config/backend/.env:/app/.env
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    tty: true
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3305:3306"
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: production
      MYSQL_USER: production
      MYSQL_PASSWORD: production123
    volumes:
      - ./db_prod:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3305
      PMA_USER: production
      PMA_PASSWORD: production123
    networks:
      - app-network
    depends_on:
      - db

  webserver:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "81:81"
    volumes:
      - ./app_frontend/build:/usr/share/nginx/frontend
      - ./app_backend:/usr/share/nginx/backend
      - ./config/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
