version: "3.7"

services:
  frontend:
    build:
      context: ./app_frontend
      dockerfile: Dockerfile
    networks:
      - app-network

  backend:
    container_name: backend
    working_dir: /var/www
    build:
      context: ./app_backend
      dockerfile: Dockerfile
    volumes:
      - ./app_backend:/var/www/backend
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    tty: true
    port:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: test
      PMA_PASSWORD: test
    networks:
      - app-network
    depends_on:
      - db

  webserver:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app_frontend/build:/usr/share/nginx/frontend
      - ./app_backend:/usr/share/nginx/backend
      - ./config/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
