version: "3.7"

services:
  backend:
    container_name: backend-staging
    build:
      context: ./app_backend
      dockerfile: Dockerfile
    working_dir: /app/backend
    depends_on:
      - db
    volumes:
      - backend:/app/backend
      - ./config/backend/.env.staging:/app/backend/.env
    networks:
      - app-network-staging

  frontend:
    container_name: frontend-staging
    build:
      context: ./app_frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/frontend
    networks:
      - app-network-staging

  db:
    container_name: db-staging
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3304:3306"
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: staging
      MYSQL_USER: staging
      MYSQL_PASSWORD: staging123
    volumes:
      - ./db_staging:/var/lib/mysql
    networks:
      - app-network-staging

  phpmyadmin:
    container_name: phpmyadmin-staging
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: staging
      PMA_PASSWORD: staging123
    networks:
      - app-network-staging
    depends_on:
      - db

  webserver:
    container_name: webserver-staging
    image: webdevops/php-nginx:8.2-alpine
    restart: unless-stopped
    tty: true
    ports:
      - "82:82"
    volumes:
      - frontend:/app/frontend
      - backend:/app/backend
      - ./config/nginx/nginx.staging.conf:/opt/docker/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - backend
      - frontend
    networks:
      - app-network-staging

networks:
  app-network-staging:
    driver: bridge

volumes:
  frontend:
  backend:
