name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  Test_Backend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./app_backend
    steps:
      - uses: actions/checkout@v3
      - name: "Show ls"
        run: "ls -la"
      - name: "Install Composer Dependency"
        uses: "composer install --no-interaction --prefer-dist --optimize-autoloader"
      - name: "Set Up Environtment"
        run: "cp .env.example .env && php artisan key:generate"
      - name: "Testing Project"
        run: "php artisan test"

  Test_Frontend:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./app_frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Testing Project"
        run: "npm run test"

  Deploy:
    needs: [Test_Backend, Test_Frontend]
    runs-on: self-hosted
    steps:
      - name: Stop Docker Containers
        run: docker-compose -f docker-compose.yaml down -v --rmi local
      - name: Build Docker Containers
        run: docker-compose -f docker-compose.yaml build
