name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  Test_Backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: "Install Composer Dependency"
        working_dir: "./app_backend"
        uses: php-actions/composer@v6
        with:
          args: install
      - name: "Set Up Environtment"
        working_dir: "./app_backend"
        run: "cp .env.example .env && php artisan key:generate"
      - name: "Testing Project"
        working_dir: "./app_backend"
        run: "php artisan test"

  Test_Frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: "Install Dependencies"
        working_dir: "./app_frontend"
      - name: "Testing Project"
        working_dir: "./app_frontend"
        run: |
          npm install
          npm run test

  Deploy:
    needs: [Test_Backend, Test_Frontend]
    runs-on: self-hosted
    steps:
      - name: Stop Docker Containers
        run: docker-compose -f docker-compose.yaml down -v --rmi local
      - name: Build Docker Containers
        run: docker-compose -f docker-compose.yaml build
