name: Production Pipeline

on:
  push:
    branches:
      - staging

jobs:
  Test_Backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: "Go to Backend Project"
        run: "cd ./app_backend"
      - name: "Install Composer"
        uses: php-actions/composer@v6
        with:
          args: install
      - name: "Run PHPUnit Tests"
        run: "vendor/bin/phpunit /tests"
      - name: "Upload Coverage Report"
        uses: codecov/codecov-action@v1

  Test_Frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: "cd ./app_frontend"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run test
      - name: "Upload Coverage Report"
        uses: codecov/codecov-action@v1

  Deploy:
    needs: [Test_Backend, Test_Frontend]
    runs-on: self-hosted
    steps:
      - name: Stop Docker Containers
        run: docker-compose -f docker-compose.yaml down -v --rmi local
      - name: Build Docker Containers
        run: docker-compose -f docker-compose.yaml build
