name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  Test Backend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: "cd ./app_backend"
      - uses: php-actions/composer@v6
        with:
          args: install
      - uses: php-actions/phpunit@v7
        with:
          args: --coverage-clover=coverage.xml
      - uses: codecov/codecov-action@v1

  Test Frontend:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: "cd ./app_frontend"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run test

  Deploy:
    needs: [Test Backend, Test Frontend]
    runs-on: self-hosted
    steps:
      - name: Stop Docker Containers
        run: docker-compose -f docker-compose.yaml down -v --rmi local
      - name: Build Docker Containers
        run: docker-compose -f docker-compose.yaml build
